spring:
  output:
      ansi:
        enabled: ALWAYS
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
server:
  port: 5000


---
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aa1qwogornl3z5.chuhdoagqbxr.us-west-2.rds.amazonaws.com:3306/ebdb